version: '3.4'
services:
  calculation:
    image: "calculation:B${BUILD_NUMBER}"
    build:
      network: host
      context: .
      args:
        PROJECT_VERSION: 1
      dockerfile: calculation-console/Dockerfile 
